keys:
  - &primary-age-key age1yx5ezcaa22krhgj568hk4hdc88t5tf9y0kq9dwjv0hz4lu2skg3suvr8du

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *primary-age-key
  