## Do not modify this file!  It was generated by 'nixos-generate-config'
## and may be overwritten by future invocations.  Please make changes
## to /etc/nixos/configuration.nix instead.

outer: {
  configurations.nixos."workstation-nixos".module =
    {
      pkgs,
      config,
      lib,
      modulesPath,
      ...
    }:
    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      boot = {
        initrd = {
          availableKernelModules = [
            "nvme"
            "xhci_pci"
            "ahci"
            "usb_storage"
            "usbhid"
            "sd_mod"
            "nvidia"
            "nvidia_modeset"
            "nvidia_uvm"
            "nvidia_drm"
            "igc" # lspci -v | grep -iA8 'network\|ethernet'
          ];

          # Remote unlock for encrypted ZFS: enable networking and SSH in initrd
          network = {
            enable = true;
            ssh = {
              enable = true;
              port = 2222; # connect with: ssh -p 2222 root@<initrd-ip>
              hostKeys = [ "/etc/ssh/ssh_host_ed25519_key" ];
              authorizedKeys = [ outer.config.repo.constants.sshPublicKey ];
              # shell = "/bin/cryptsetup-askpass";
            };
            udhcpc.enable = false;
          };
          # Copy the host private key into the initrd image
          secrets = {
            "/etc/ssh/ssh_host_ed25519_key" = "/etc/ssh/ssh_host_ed25519_key";
          };
        };

        kernelModules = [
          "kvm-amd"
        ];

        kernelParams = [
          "acpi_enforce_resources=lax"
          "acpi_osi=\"!Windows 2015\""
          "amd_pstate=active"
          "nvidia_drm.modeset=1"
          "nvidia.NVreg_PreserveVideoMemoryAllocations=1"
          "zfs.zfs_arc_max=4294967296" # 4 GiB https://nixos.wiki/wiki/ZFS
          "zfs.zfs_prefetch_disable=1"
          "ip=192.168.1.40::192.168.1.1:255.255.255.0:workstation-nixos::none"
        ];

        # Use the systemd-boot EFI boot loader.
        loader = {
          systemd-boot.enable = true;
          efi.canTouchEfiVariables = true;
        };
      };

      powerManagement = {
        enable = true;
        cpuFreqGovernor = "powersave";
      };

      services.power-profiles-daemon.enable = true;

      fileSystems = {
        "/" = {
          device = "zroot/system/root";
          fsType = "zfs";
        };

        "/var" = {
          device = "zroot/system/var";
          fsType = "zfs";
        };

        "/shared/games" = {
          device = "zroot/shared/games";
          fsType = "zfs";
        };

        "/nix" = {
          device = "zroot/local/nix";
          fsType = "zfs";
        };

        "/home/lkshrsch" = {
          device = "zroot/user/home/lkshrsch";
          fsType = "zfs";
        };

        "/boot" = {
          device = "/dev/disk/by-partuuid/d7167427-97f5-492e-8abe-a2f75030d774";
          fsType = "vfat";
          options = [
            "fmask=0077"
            "dmask=0077"
            "defaults"
          ];
        };
      };

      swapDevices = [
        {
          device = "/dev/disk/by-partlabel/Linux\\\\x20swap";
          randomEncryption = true;
        }
      ];

      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
