# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  constants,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usb_storage"
        "usbhid"
        "sd_mod"
        "nvidia"
        "nvidia_modeset"
        "nvidia_uvm"
        "nvidia_drm"
        "igc" # lspci -v | grep -iA8 'network\|ethernet'
      ];
      kernelModules = [ ];

      # Remote unlock for encrypted ZFS: enable networking and SSH in initrd
      network = {
        enable = true;
        ssh = {
          enable = true;
          port = 2222; # connect with: ssh -p 2222 root@<initrd-ip>
          hostKeys = [ "/etc/ssh/ssh_host_ed25519_key" ];
          authorizedKeys = [ constants.sshPublicKey ];
          # shell = "/bin/cryptsetup-askpass";
        };
        udhcpc.enable = false;
      };
      # Copy the host private key into the initrd image
      secrets = {
        "/etc/ssh/ssh_host_ed25519_key" = "/etc/ssh/ssh_host_ed25519_key";
      };
    };

    kernelModules = [
      "kvm-amd"
    ];
    blacklistedKernelModules = [ ];

    kernelParams = [
      "acpi_enforce_resources=lax"
      "amd_pstate=guided"
      "nvidia_drm.modeset=1"
      "nvidia.NVreg_PreserveVideoMemoryAllocations=1"
      "zfs.zfs_arc_max=4294967296" # 4 GiB https://nixos.wiki/wiki/ZFS
      "zfs.zfs_prefetch_disable=1"
      "ip=192.168.1.40::192.168.1.1:255.255.255.0:workstation-nixos::none"
    ];
    extraModulePackages = [ ];

    # ZFS support (ensures ZFS is included in initrd too)
    supportedFilesystems = [ "zfs" ];
  };

  powerManagement = {
    enable = true;
    cpuFreqGovernor = "schedutil";
  };

  fileSystems."/" = {
    device = "zroot/system/root";
    fsType = "zfs";
  };

  fileSystems."/var" = {
    device = "zroot/system/var";
    fsType = "zfs";
  };

  fileSystems."/shared/games" = {
    device = "zroot/shared/games";
    fsType = "zfs";
  };

  fileSystems."/nix" = {
    device = "zroot/local/nix";
    fsType = "zfs";
  };

  fileSystems."/home/lkshrsch" = {
    device = "zroot/user/home/lkshrsch";
    fsType = "zfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/85D5-EFB5";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
      "umask=0077"
      "defaults"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/f00a98eb-9c92-4d75-8009-5ab76504c274"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
