# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd.availableKernelModules = [
      "nvme"
      "xhci_pci"
      "ahci"
      "usb_storage"
      "usbhid"
      "sd_mod"
      "nvidia"
      "nvidia_modeset"
      "nvidia_uvm"
      "nvidia_drm"
    ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    kernelParams = [
      "pcie_aspm=force"
      "amd_pstate=guided"
      "nvidia_drm.modeset=1"
      "nvidia.NVreg_PreserveVideoMemoryAllocations=1"
      "nvidia.NVreg_DynamicPowerManagement=0x02"
      "zfs.zfs_arc_max=4294967296" # 4 GiB https://nixos.wiki/wiki/ZFS
      "zfs.zfs_prefetch_disable=1"
    ];
    extraModulePackages = [ ];

    # ZFS support
    supportedFilesystems = [ "zfs" ];
  };

  powerManagement = {
    enable = true;
    cpuFreqGovernor = "schedutil";
  };

  fileSystems."/" =
    {
      device = "zroot/system/root";
      fsType = "zfs";
    };

  fileSystems."/var" =
    {
      device = "zroot/system/var";
      fsType = "zfs";
    };

  fileSystems."/shared/games" =
    {
      device = "zroot/shared/games";
      fsType = "zfs";
    };

  fileSystems."/shared/docker" =
    {
      device = "zroot/shared/docker";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    {
      device = "zroot/local/nix";
      fsType = "zfs";
    };

  fileSystems."/home/lkshrsch" =
    {
      device = "zroot/user/home/lkshrsch";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/85D5-EFB5";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" "umask=0077" "defaults" ];
    };

  swapDevices =
    [
      { device = "/dev/disk/by-uuid/f00a98eb-9c92-4d75-8009-5ab76504c274"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
